# Generated by Django 3.2.13 on 2022-05-09 11:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('inventario', '0001_initial'),
        ('servicio', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='erp_factura',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('razon_social', models.CharField(blank=True, max_length=300, null=True, verbose_name='Razón Social')),
                ('identificacion', models.CharField(blank=True, max_length=13, null=True, verbose_name='Cédula o Ruc')),
                ('cellphone', models.CharField(blank=True, max_length=10, null=True, verbose_name='Número Celular')),
                ('address', models.CharField(blank=True, max_length=320, null=True, verbose_name='Dirección')),
                ('reference', models.CharField(blank=True, max_length=320, null=True, verbose_name='Referencia de dirección')),
                ('subtotal', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10, null=True, verbose_name='Subtotal')),
                ('iva_total', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10, null=True, verbose_name='Iva Total')),
                ('ice_total', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10, null=True, verbose_name='Ice Total')),
                ('descuento_total', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10, null=True, verbose_name='Descuento Total')),
                ('total', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10, null=True, verbose_name='Total')),
                ('fecha', models.DateTimeField(auto_now_add=True, null=True)),
                ('usuario_registro', models.CharField(editable=False, max_length=50)),
                ('usuario_modificacion', models.CharField(blank=True, editable=False, max_length=50, null=True)),
                ('fecha_registro', models.DateTimeField(auto_now_add=True, null=True)),
                ('fecha_modificacion', models.DateTimeField(auto_now_add=True, null=True)),
                ('estado', models.CharField(choices=[('A', 'Generada'), ('B', 'Generada Pendiente de pago'), ('C', 'Eliminada'), ('D', 'Contabilizada')], default='A', max_length=2, verbose_name='Estado')),
                ('forma_pago', models.CharField(choices=[('A', 'Efectivo'), ('B', 'Transferencia'), ('C', 'Cuotas')], default='A', max_length=2, verbose_name='Forma de Pago')),
                ('tipo_venta', models.CharField(choices=[('A', 'Consumidor'), ('B', 'Mayorista')], default='A', max_length=2, verbose_name='Tipo de Venta')),
                ('observacion', models.CharField(blank=True, max_length=5000, null=True, verbose_name='Observación')),
                ('id_cliente', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='relacion_cliente_factura', to=settings.AUTH_USER_MODEL, to_field='email', verbose_name='Cliente')),
                ('id_orden', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='relacion_orden', to=settings.AUTH_USER_MODEL, verbose_name='Orden')),
            ],
            options={
                'verbose_name': 'Factura',
                'verbose_name_plural': 'Facturas',
                'db_table': 'erp_factura',
            },
        ),
        migrations.CreateModel(
            name='erp_factura_detalle',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10, null=True, verbose_name='Cantidad')),
                ('precio', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10, null=True, verbose_name='Subtotal')),
                ('subtotal', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10, null=True, verbose_name='Subtotal')),
                ('iva', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10, null=True, verbose_name='Iva')),
                ('ice', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10, null=True, verbose_name='Ice')),
                ('descuento', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10, null=True, verbose_name='Descuento')),
                ('total', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10, null=True, verbose_name='Total')),
                ('usuario_registro', models.CharField(editable=False, max_length=50)),
                ('usuario_modificacion', models.CharField(blank=True, editable=False, max_length=50, null=True)),
                ('fecha_registro', models.DateTimeField(auto_now_add=True, null=True)),
                ('fecha_modificacion', models.DateTimeField(auto_now_add=True, null=True)),
                ('estado', models.BooleanField(default=True)),
                ('id_factura', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='relacion_factura_detalle', to='facturacion.erp_factura', verbose_name='Factura')),
                ('id_producto', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='relacion_detall_producto', to='inventario.erp_producto', verbose_name='Producto')),
                ('id_servicio', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='relacion_servicio', to='servicio.erp_servicio_tecnico', verbose_name='Servicio')),
            ],
            options={
                'verbose_name': 'Detalle de Facturas',
                'verbose_name_plural': 'Detalle de Facturas',
                'db_table': 'erp_factura_detalle',
            },
        ),
    ]
